version: "3"

services:
  db:
    container_name: "monoero-node-explorer-db"
    hostname: postgres
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=node
      - POSTGRES_USER=node
      - POSTGRES_PASSWORD=node
    ports:
      - 5432:5432
